[versions]
walkin-message = "1.0.3-SNAPSHOT"
hutool = "6.0.0-M11"
tower-logging = "1.0.0-SNAPSHOT"
spring-boot = "3.2.3"
camel = "4.3.0"
postgresql = "42.7.2"
kotlin = "1.9.22"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

graalvm-buildtools = { id = "org.graalvm.buildtools.native", version = "0.9.27" }
